name: CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build-and-test:
    # Run on macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio pytest-mock httpx requests

      # Run tests
      - name: Run tests
        run: |
          pytest noble_tls/tests

  release:
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build-and-publish:
      needs: release
      if: startsWith(github.ref, 'refs/tags/')
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.10'

        - name: Install pypi-publish dependencies
          run: |
            python -m pip install --upgrade pip setuptools wheel twine

        - name: Build package
          run: |
            python setup.py sdist bdist_wheel

        - name: Publish package to PyPI
          env:
            PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
          run: |
            twine upload dist/* --skip-existing -u __token__ -p $PYPI_API_TOKEN
